// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using Mona.SaaS.Core.Constants;
using System;

namespace Mona.SaaS.Core.Models.Events.V_2021_10_01
{
    /// <summary>
    /// Event generated by the Marketplace when a subscription is cancelled/unsubscribed.
    /// </summary>
    public class SubscriptionCanceled : BaseSubscriptionEvent
    {
        public SubscriptionCanceled() : base(EventTypes.SubscriptionCanceled) { }

        public SubscriptionCanceled(Subscription subscription, string operationId, DateTime? operationDateTimeUtc = null)
            : base(EventTypes.SubscriptionCanceled, subscription, operationId, operationDateTimeUtc) { }
    }
}