// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using Mona.SaaS.Core.Constants;
using Newtonsoft.Json;
using System;
using System.Text.Json.Serialization;

namespace Mona.SaaS.Core.Models.Events.V_2021_10_01
{
    /// <summary>
    /// Event generated by Azure Marketplace when the subscription seats quantity is updated.
    /// </summary>
    public class SubscriptionSeatQuantityChanged : BaseSubscriptionEvent
    {
        public SubscriptionSeatQuantityChanged() : base(EventTypes.SubscriptionSeatQuantityChanged) { }

        public SubscriptionSeatQuantityChanged(Subscription subscription, string operationId, int? newSeatQuantity, DateTime? operationDateTimeUtc = null)
            : base(EventTypes.SubscriptionSeatQuantityChanged, subscription, operationId, operationDateTimeUtc)
        {
            NewSeatQuantity = newSeatQuantity;
        }

        [JsonProperty("New Seat Quantity")]
        [JsonPropertyName("New Seat Quantity")]
        public int? NewSeatQuantity { get; set; }
    }
}