// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Mona.SaaS.Core.Models.Events.V_2021_05_01
{
    using Mona.SaaS.Core.Constants;
    using System;

    /// <summary>
    /// Event generated by Azure Marketplace when a subscription is renewed.
    /// </summary>
    public class SubscriptionRenewed : BaseSubscriptionEvent
    {
        public SubscriptionRenewed() : base(EventTypes.SubscriptionRenewed) { }

        public SubscriptionRenewed(Subscription subscription, string operationId, DateTime? operationDateTimeUtc = null)
            : base(EventTypes.SubscriptionRenewed, subscription, operationId, operationDateTimeUtc) { }
    }
}
