// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using Mona.SaaS.Core.Constants;
using System;

namespace Mona.SaaS.Core.Models.Events.V_2021_05_01
{
    /// <summary>
    /// Event generated by Azure Marketplace when a subscription is suspended due to non-payment.
    /// </summary>
    public class SubscriptionSuspended : BaseSubscriptionEvent
    {
        public SubscriptionSuspended() : base(EventTypes.SubscriptionSuspended) { }

        public SubscriptionSuspended(Subscription subscription, string operationId, DateTime? operationDateTimeUtc = null)
            : base(EventTypes.SubscriptionSuspended, subscription, operationId, operationDateTimeUtc) { }
    }
}