// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using Mona.SaaS.Core.Constants;
using System;

namespace Mona.SaaS.Core.Models.Events.V_2021_05_01
{
    /// <summary>
    /// Event generated by Azure Marketplace when a subscription is reinstated.
    /// </summary>
    public class SubscriptionReinstated : BaseSubscriptionEvent
    {
        public SubscriptionReinstated() : base(EventTypes.SubscriptionReinstated) { }

        public SubscriptionReinstated(Subscription subscription, string operationId, DateTime? operationDateTimeUtc = null)
            : base(EventTypes.SubscriptionReinstated, subscription, operationId, operationDateTimeUtc) { }
    }
}